### ISSUE TITLE
DailyVideoView should be transformed in the updateUIView so when the user's camera is switched to the back camera, it is not mirrored

### ISSUE THREAD

**Issue by BobbyRohweder** [daily-demos/daily-ios-starter-kit#14]
makeUIView is only called when the view is created.

The code can probably be like this instead:
```
func updateUIView(_ videoView: VideoView, context: Context) {
    videoView.track = track
    videoView.videoScaleMode = videoScaleMode
    videoView.transform = CGAffineTransform(scaleX: isMirrored ? -1 : 1, y: 1) // <= moved here

    // Hide the view if we do not have a track.
    videoView.isHidden = track == nil
}
```

**Comment by marcisme** [comment]
@BobbyRohweder Thanks for the report! I recently made a change that was intended to fix this, and apparently I was seeing backwards when I tested it. 🙃 Updating the transform as you've proposed should work, though we get a mirrored frame before the facing mode changes. I've opened an internal issue to investigate that behavior. Thanks again.
